<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net5.0</TargetFramework>
    <UserSecretsId>d93c9c18-950e-464c-91ce-318c5164af10</UserSecretsId>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	 
	  
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Models\Data\**" />
    <Compile Remove="Views\Shared\Components\GroupAssignment\**" />
    <Content Remove="Models\Data\**" />
    <Content Remove="Views\Shared\Components\GroupAssignment\**" />
    <EmbeddedResource Remove="Models\Data\**" />
    <EmbeddedResource Remove="Views\Shared\Components\GroupAssignment\**" />
    <None Remove="Models\Data\**" />
    <None Remove="Views\Shared\Components\GroupAssignment\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Components\AvailableJobTitlesViewComponent.cs" />
    <Compile Remove="Components\JobTitleAssignmentViewComponent.cs" />
    <Compile Remove="Components\SiteTextViewComponent.cs" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="Views\SystemReview\Index_old.cshtml" />
  </ItemGroup>

	
	

  <ItemGroup>
    <PackageReference Include="bootstrap" Version="5.1.2" />
    <PackageReference Include="EfCore.SchemaCompare" Version="5.1.4">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="EntityFramework" Version="6.4.4" />
    <PackageReference Include="EntityFramework.Functions" Version="1.5.0" />
    <PackageReference Include="ErikEJ.EntityFrameworkCore.DgmlBuilder" Version="5.0.0" />
    <PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="5.0.26" />
    <PackageReference Include="MailKit" Version="2.15.0" />
    <PackageReference Include="Microsoft.AspNetCore.DataProtection.Extensions" Version="5.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.NewtonsoftJson" Version="5.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Razor.RuntimeCompilation" Version="5.0.11" />
    <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.2.0" />
    <PackageReference Include="Microsoft.AspNetCore.Razor.Runtime" Version="2.2.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Analyzers" Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="5.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="5.0.11" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="5.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Console" Version="5.0.0" />
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="5.0.2" />
    <PackageReference Include="PagedList.Core.Mvc" Version="3.0.0" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />

    <PackageReference Include="X.PagedList" Version="8.1.0" />
    <PackageReference Include="X.PagedList.Mvc.Core" Version="8.1.0" />
    <PackageReference Include="X.PagedList.Web.Common" Version="8.0.7" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\css\" />
    <Folder Include="wwwroot\js\" />
    <Folder Include="wwwroot\lib\bootstrap\" />
    <Folder Include="wwwroot\lib\bootstrap\dist\css\" />
    <Folder Include="wwwroot\lib\bootstrap\dist\js\" />
    <Folder Include="wwwroot\lib\jquery-validation-unobtrusive\" />
    <Folder Include="wwwroot\lib\jquery-validation\" />
    <Folder Include="wwwroot\lib\jquery-validation\dist\" />
    <Folder Include="wwwroot\lib\jquery\" />
    <Folder Include="wwwroot\lib\jquery\dist\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\StaffManagement.Data\StaffManagement.Data.csproj" />
  </ItemGroup>

</Project>
