using System.Text;
using ApiCallMonitor.Core.Models;

namespace ApiCallMonitor.Core.Export;

/// <summary>Default <see cref="IPowerShellScriptGenerator"/>. Emits a single self-contained .ps1
/// file: a small <c>Invoke-ConfiguredApiCall</c> helper (built on <c>Invoke-WebRequest</c>, which
/// works the same way on Windows PowerShell 5.1 and PowerShell 7+) followed by one call to it per
/// enabled call, in order, and a summary/exit-code block so the script is CI/scheduled-task
/// friendly (exit 0 = all calls succeeded, exit 1 = at least one failed).</summary>
public class PowerShellScriptGenerator : IPowerShellScriptGenerator
{
    public string Generate(ApiCallCollection collection)
    {
        var enabledCalls = collection.Calls
            .Where(c => c.Enabled)
            .OrderBy(c => c.Order)
            .ToList();

        var sb = new StringBuilder();

        sb.AppendLine("#requires -Version 5.1");
        sb.AppendLine("<#");
        sb.AppendLine($"    {EscapeCommentLine(collection.Name)}");
        sb.AppendLine("    Generated by API Call Monitor - replays this collection's enabled calls, in order, outside the app.");
        sb.AppendLine($"    Generated at {DateTime.UtcNow:u}. Re-download/regenerate after changing the collection to pick up edits.");
        sb.AppendLine("    Exits 0 if every call succeeded, 1 if any call failed.");
        sb.AppendLine("#>");
        sb.AppendLine();
        sb.AppendLine("Set-StrictMode -Version Latest");
        sb.AppendLine("$ErrorActionPreference = 'Stop'");
        sb.AppendLine();

        AppendHelperFunction(sb);

        sb.AppendLine();
        sb.AppendLine("$results = @()");
        sb.AppendLine();

        if (enabledCalls.Count == 0)
        {
            sb.AppendLine("Write-Host 'No enabled calls in this collection.' -ForegroundColor Yellow");
        }
        else
        {
            foreach (var call in enabledCalls)
            {
                AppendCallInvocation(sb, call);
            }
        }

        sb.AppendLine("if ($results.Count -gt 0) {");
        sb.AppendLine("    Write-Host ''");
        sb.AppendLine("    $results | Format-Table Name, Success, StatusCode, DurationMs -AutoSize | Out-Host");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("$failedCount = @($results | Where-Object { -not $_.Success }).Count");
        sb.AppendLine("if ($failedCount -gt 0) {");
        sb.AppendLine("    Write-Host \"$failedCount of $($results.Count) call(s) failed.\" -ForegroundColor Red");
        sb.AppendLine("    exit 1");
        sb.AppendLine("}");
        sb.AppendLine();
        sb.AppendLine("Write-Host \"All $($results.Count) call(s) succeeded.\" -ForegroundColor Green");
        sb.AppendLine("exit 0");

        return sb.ToString();
    }

    private static void AppendHelperFunction(StringBuilder sb)
    {
        // Plain (non-interpolated) raw string: every $ below is literal PowerShell, not C#.
        sb.Append("""
            function Invoke-ConfiguredApiCall {
                param(
                    [Parameter(Mandatory)] [string] $Name,
                    [Parameter(Mandatory)] [string] $Method,
                    [Parameter(Mandatory)] [string] $Url,
                    [hashtable] $Headers = @{},
                    [string] $Body,
                    [string] $ContentType,
                    [int] $TimeoutSeconds = 30
                )

                Write-Host "==> $Name ($Method $Url)" -ForegroundColor Cyan
                $stopwatch = [System.Diagnostics.Stopwatch]::StartNew()

                $requestParams = @{
                    Uri             = $Url
                    Method          = $Method
                    Headers         = $Headers
                    TimeoutSec      = $TimeoutSeconds
                    UseBasicParsing = $true
                }
                if ($Body) {
                    $requestParams.Body = $Body
                    if ($ContentType) { $requestParams.ContentType = $ContentType }
                }

                try {
                    $response = Invoke-WebRequest @requestParams
                    $stopwatch.Stop()
                    Write-Host "    OK - $([int]$response.StatusCode) in $($stopwatch.ElapsedMilliseconds) ms" -ForegroundColor Green
                    return [pscustomobject]@{
                        Name       = $Name
                        Success    = $true
                        StatusCode = [int]$response.StatusCode
                        DurationMs = $stopwatch.ElapsedMilliseconds
                        Response   = $response.Content
                    }
                }
                catch {
                    $stopwatch.Stop()
                    $statusCode = $null
                    if ($_.Exception.Response) {
                        $statusCode = [int]$_.Exception.Response.StatusCode
                    }
                    Write-Host "    FAILED - $statusCode $($_.Exception.Message) in $($stopwatch.ElapsedMilliseconds) ms" -ForegroundColor Red
                    return [pscustomobject]@{
                        Name       = $Name
                        Success    = $false
                        StatusCode = $statusCode
                        DurationMs = $stopwatch.ElapsedMilliseconds
                        Error      = $_.Exception.Message
                    }
                }
            }
            """);
        sb.AppendLine();
    }

    private static void AppendCallInvocation(StringBuilder sb, ApiCallDefinition call)
    {
        sb.AppendLine($"# {EscapeCommentLine(call.Name)}");
        sb.AppendLine("$headers = @{}");
        foreach (var (name, value) in call.ParseHeaders())
        {
            sb.AppendLine($"$headers['{EscapeSingleQuoted(name)}'] = '{EscapeSingleQuoted(value)}'");
        }

        sb.AppendLine("$results += Invoke-ConfiguredApiCall `");
        sb.AppendLine($"    -Name '{EscapeSingleQuoted(call.Name)}' `");
        sb.AppendLine($"    -Method '{call.Method.ToString().ToUpperInvariant()}' `");
        sb.AppendLine($"    -Url '{EscapeSingleQuoted(call.Url)}' `");
        sb.AppendLine("    -Headers $headers `");

        if (!string.IsNullOrEmpty(call.Body))
        {
            // A here-string rather than an escaped single-quoted string, since bodies are typically
            // multi-line JSON that would otherwise need every embedded ' and newline handled.
            sb.AppendLine("    -Body @'");
            sb.AppendLine(call.Body);
            sb.AppendLine("'@ `");
            sb.AppendLine($"    -ContentType '{EscapeSingleQuoted(call.ContentType)}' `");
        }

        sb.AppendLine($"    -TimeoutSeconds {Math.Max(1, call.TimeoutSeconds)}");
        sb.AppendLine();
    }

    private static string EscapeSingleQuoted(string value) => value.Replace("'", "''");

    private static string EscapeCommentLine(string value) => value.Replace("#>", "# >");
}
