// <auto-generated />
using System;
using DFSSlateAnalyzerData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DFSSlateAnalyzerAPI.Migrations
{
    [DbContext(typeof(DFSSlateAnalyzerContext))]
    [Migration("20230203043526_2-2-2")]
    partial class _222
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Contest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("ContestID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PercentComplete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contests");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Entry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("ContestID")
                        .HasColumnType("bigint");

                    b.Property<long>("EntryID")
                        .HasColumnType("bigint");

                    b.Property<string>("Lineup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<string>("TimeRemaining")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("ContestID");

                    b.HasIndex("OwnerName");

                    b.ToTable("Entries");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.EntryMember", b =>
                {
                    b.Property<long>("EntryID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntryMemberPlayerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LineupSlot")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EntryID", "EntryMemberPlayerName");

                    b.ToTable("EntryMembers");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Owner", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Owners");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Player", b =>
                {
                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("ContestID")
                        .HasColumnType("int");

                    b.Property<string>("Drafted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FPTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProjectedPoints")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RosterPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PlayerName");

                    b.HasIndex("ContestID");

                    b.ToTable("Players");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Entry", b =>
                {
                    b.HasOne("DFSSlateAnalyzerData.Data.Contest", "Contest")
                        .WithMany("Entries")
                        .HasForeignKey("ContestID")
                        .HasPrincipalKey("ContestID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DFSSlateAnalyzerData.Data.Owner", null)
                        .WithMany("Entries")
                        .HasForeignKey("OwnerName");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.EntryMember", b =>
                {
                    b.HasOne("DFSSlateAnalyzerData.Data.Entry", "Entry")
                        .WithMany("EntryMembers")
                        .HasForeignKey("EntryID")
                        .HasPrincipalKey("EntryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Player", b =>
                {
                    b.HasOne("DFSSlateAnalyzerData.Data.Contest", null)
                        .WithMany("ContestPlayers")
                        .HasForeignKey("ContestID");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Contest", b =>
                {
                    b.Navigation("ContestPlayers");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Entry", b =>
                {
                    b.Navigation("EntryMembers");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Owner", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
