// <auto-generated />
using System;
using DFSSlateAnalyzerData;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DFSSlateAnalyzerAPI.Migrations
{
    [DbContext(typeof(DFSSlateAnalyzerContext))]
    [Migration("20230213020324_2-11-22-6666666667774643664335433")]
    partial class _211226666666667774643664335433
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Contest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("ContestID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("Fee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("PercentComplete")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("Size")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("Contest", "dfs");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.DFSPlayer", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("BMFirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BMLastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DKPlayerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerID")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("RosterPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Team")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DFSPlayer", "dfs");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Entry", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<long>("ContestID")
                        .HasColumnType("bigint");

                    b.Property<long>("EntryID")
                        .HasColumnType("bigint");

                    b.Property<string>("Lineup")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OwnerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Rank")
                        .HasColumnType("int");

                    b.Property<decimal?>("TimeRemaining")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ID");

                    b.HasIndex("ContestID");

                    b.HasIndex("OwnerName");

                    b.ToTable("Entry", "dfs");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.EntryMember", b =>
                {
                    b.Property<long>("ContestID")
                        .HasColumnType("bigint");

                    b.Property<long>("EntryID")
                        .HasColumnType("bigint");

                    b.Property<string>("EntryMemberPlayerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("LineupSlot")
                        .HasColumnType("int");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContestID", "EntryID", "EntryMemberPlayerName");

                    b.HasIndex("EntryID");

                    b.ToTable("EntryMember", "dfs");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Owner", b =>
                {
                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Name");

                    b.ToTable("Owner", "dfs");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Player", b =>
                {
                    b.Property<string>("PlayerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("ContestID")
                        .HasColumnType("bigint");

                    b.Property<decimal?>("BMProjection")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Drafted")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EntryMemberPlayerName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("FPTS")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OPP")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PlayerID")
                        .HasColumnType("int");

                    b.Property<decimal?>("Points")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Position")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ProjectedPoints")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RosterPosition")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salary")
                        .HasColumnType("nvarchar(max)");

                    b.Property<long?>("entryMemberContestID")
                        .HasColumnType("bigint");

                    b.Property<long?>("entryMemberEntryID")
                        .HasColumnType("bigint");

                    b.HasKey("PlayerName", "ContestID");

                    b.HasIndex("ContestID");

                    b.HasIndex("PlayerID")
                        .IsUnique()
                        .HasFilter("[PlayerID] IS NOT NULL");

                    b.HasIndex("entryMemberContestID", "entryMemberEntryID", "EntryMemberPlayerName");

                    b.ToTable("Player", "dfs");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Entry", b =>
                {
                    b.HasOne("DFSSlateAnalyzerData.Data.Contest", "Contest")
                        .WithMany("Entries")
                        .HasForeignKey("ContestID")
                        .HasPrincipalKey("ContestID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DFSSlateAnalyzerData.Data.Owner", null)
                        .WithMany("Entries")
                        .HasForeignKey("OwnerName");

                    b.Navigation("Contest");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.EntryMember", b =>
                {
                    b.HasOne("DFSSlateAnalyzerData.Data.Entry", "Entry")
                        .WithMany("EntryMembers")
                        .HasForeignKey("EntryID")
                        .HasPrincipalKey("EntryID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entry");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Player", b =>
                {
                    b.HasOne("DFSSlateAnalyzerData.Data.Contest", "Contest")
                        .WithMany("ContestPlayers")
                        .HasForeignKey("ContestID")
                        .HasPrincipalKey("ContestID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DFSSlateAnalyzerData.Data.DFSPlayer", "DFSPlayer")
                        .WithOne("Player")
                        .HasForeignKey("DFSSlateAnalyzerData.Data.Player", "PlayerID")
                        .HasPrincipalKey("DFSSlateAnalyzerData.Data.DFSPlayer", "PlayerID")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.HasOne("DFSSlateAnalyzerData.Data.EntryMember", "entryMember")
                        .WithMany()
                        .HasForeignKey("entryMemberContestID", "entryMemberEntryID", "EntryMemberPlayerName");

                    b.Navigation("Contest");

                    b.Navigation("DFSPlayer");

                    b.Navigation("entryMember");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Contest", b =>
                {
                    b.Navigation("ContestPlayers");

                    b.Navigation("Entries");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.DFSPlayer", b =>
                {
                    b.Navigation("Player");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Entry", b =>
                {
                    b.Navigation("EntryMembers");
                });

            modelBuilder.Entity("DFSSlateAnalyzerData.Data.Owner", b =>
                {
                    b.Navigation("Entries");
                });
#pragma warning restore 612, 618
        }
    }
}
